### ISSUE TITLE
Doesn't work on local files

### ISSUE THREAD

**Issue by Damien-B** [CSWilson/Viewport-Dimensions#10]
It appears that the plugin doesn't work when you resize the window of a local file.
I believe most of people are using it while integrating on local, so it may be a major issue.

**Comment by rzw** [comment]
Interesting to know. Keeps you from going on a debugging tour. In that sense it's a major issue.
Of course browsers generally have tabs so the work-around is simple.  In that sense it's a minor.

So this "feature" should be mentioned in the description.

**Comment by szabgab** [comment]
According to the UPDATE info in the Chrome webstore this issue was fixed in v0.0.4 but as of v0.0.7 it does not seem to work. This was the fix back then: https://github.com/CSWilson/Viewport-Dimensions/commit/ce1592b5d9ca2ba0337047e5230344f5612c88ec

**Comment by samfortunato** [comment]
Still doesn't work on local files.

Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
